# /meta-display/docker-compose.yml
---
version: '3.8'
services:
  db:
    container_name: 'wordpress-db'
    image: 'mariadb:latest'
    volumes:
      - '.data/mysql:/var/lib/mysql'
    ports:
      - 18766:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: wordpress_db
      MARIADB_USER: wordpress_user
      MARIADB_PASSWORD: wordpress_password
  wordpress:
    container_name: 'wordpress'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '8800:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - "./wordpress:/var/www/html"
      - "./plugins:/var/www/html/wp-content/plugins"
      - "./themes:/var/www/html/wp-content/themes"